inc/class-bootstrap-5-navwalker.php, js/theme.js
Based on the issue that @craftwerkberlin opened in the navwalker, https://github.com/AlexWebLab/bootstrap-5-wordpress-navbar-walker/issues/7.
=> Build "current_page_parent" and "current-post-ancestor" check into the navwalker

woocommerce/myaccount/payment-methods.php
Hi !
Can you change line 79 class "button" to "btn btn-outline-primary" to have the same style than the other buttons ?
=> Change button class for payment-methods

woocommerce/woocommerce-functions.php
After registration is completed or in case of an error, the My Account page should be displayed to show the user the error or the activation email note.
=> Add redirect to my-account after registration

css/scss/bootscore_woocommerce/_wc_loop.scss, woocommerce/content-product-cat.php, woocommerce/woocommerce-functions.php
- Fixes https://github.com/bootscore/bootscore/issues/49
- Button and badge done by filter (woocommerce-functions.php)
- `card-img-top` done by `@extend` in _wc_loop.scss
=> Fix WooCommerce sub categories in loop

.gitignore, inc/scss-compiler.php
Connected to #97.
I've tested it on a local environment, and all seems to work, also for the child theme. @crftwrk could you try it out on a webserver environment? I currently don't have one set up for testing this.
=> Add scss sourcemap support

scss/bootscore/_markups.scss
This should fix #143 for the future.
=> Make footer stick to bottom

functions.php
Update bootscore_pagination() to default page number to 1
=> Update bootscore_pagination() in functions.php

inc/template-tags.php
Closes https://github.com/bootscore/bootscore/issues/92
=> Remove empty IE alert function

scss/bootscore_woocommerce/_wc_offcanvas_cart.scss
Just some tiny improvements. We can use Bootstrap classes instead, but to avoid breaking changes in header.php this is done by a bit CSS instead.
=> Improve offcanvas cart-loader

scss/bootscore_woocommerce/_wc_checkout.scss, scss/bootscore_woocommerce/_wc_loop.scss, scss/bootscore_woocommerce/_wc_product.scss
Just a minor bug fix, nothing special
=> Fix border-radius in checkout #payment card

style.css
Closes https://github.com/bootscore/bootscore/issues/229
=> Add scss notice to style.css

scss/bootscore_woocommerce/_wc_checkout.scss
=> Set checkout shipping table heading to top

single-templates/single-full-width-image.php, single-templates/single-sidebar-left.php, single-templates/single-sidebar-none.php, single.php
Closes https://github.com/bootscore/bootscore/issues/248
Discussion https://github.com/bootscore/bootscore/discussions/249
This PR changes  in `single-*.php` the `the_author_posts_link();` to `bootscore_author();` to use the same function there like in the loop.
=> single.php meta author same as in loop

inc/template-tags.php
Closes https://github.com/bootscore/bootscore/issues/257
=> Readd empty IE function

functions.php, scss/_bscore_woocommerce.scss, scss/bootscore/_breadcrumb.scss, scss/bootscore_woocommerce/_wc_breadcrumb.scss, woocommerce/woocommerce-functions.php
Update standard and WC breadcrumbs to Bootstrap 5.2 spec.
Divider can now be styled with CSS :before
=> Feature breadcrumbs

functions.php, scss/_bscore_style.scss, scss/_bscore_woocommerce.scss, scss/bootscore_woocommerce/_wc_breadcrumb.scss, woocommerce/woocommerce-functions.php
Adding some classes to https://github.com/bootscore/bootscore/pull/274
=> Improve breadcrumb

scss/bootscore/_colors.scss, scss/bootscore_woocommerce/_wc_colors.scss
=> Fix nonstandard prefix for ::selection

woocommerce/myaccount/my-account-offcanvas.php
=> Update password message for my account offcanvas.

scss/bootscore_woocommerce/_wc_qty_btn.scss
Closes https://github.com/bootscore/bootscore/issues/393
=> Fix extend compound selectors

functions.php
Deleted line 424 in fucntions.php.
=> Remove duplicated nav closing tag in the_breadcrumb().

functions.php
Registers strings in bootscore_pagination() in bootscore text domain.
=> Make pagination translation-ready

functions.php
As we've discussed in the past: having a short for inserting font awesome symbols instead of having to type the complete html code be an advantage
=> Add a short code for inserting font awesome signs

404.php, archive.php, footer.php, header-woocommerce.php, header.php, index.php, page-templates/page-blank-with-container.php, page-templates/page-full-width-image.php, page-templates/page-sidebar-left.php, page-templates/page-sidebar-none.php, page.php, search.php, searchform.php, single.php, woocommerce.php, woocommerce/woocommerce-functions.php
Replaced all the `<?php echo` with `<?=` as this looks cleaner to me.
I skipped the WooCommerce files, as imo it's best to keep them as "original" as possible to ease updating them.
=> Replace PHP echo's with shorthand

inc/template-tags.php
printf() missing a format string...
=> Fix bootscore_category() failing to output categories

functions.php
| <img width="491" alt="Bildschirmfoto 2023-05-19 um 17 33 28" src="https://github.com/bootscore/bootscore/assets/51531217/dab617df-c237-46b7-bc83-5b8e81dbe9ba">  | <img width="490" alt="Bildschirmfoto 2023-05-19 um 17 33 57" src="https://github.com/bootscore/bootscore/assets/51531217/01eb418c-f8aa-41fb-b270-b883b7c62c13">  |
=> Password protected post form as input-group

README.md, scss/bootscore_woocommerce/_wc_checkout.scss, woocommerce/content-product.php, woocommerce/loop/loop-start.php, woocommerce/wc-functions.php
- Added a products class to the wc loop start
- Replaced mb-4 with gutters
@crftwrk If you got any small changes you wanna do, maybe this is a nice moment? :D You could add to the PR.
Closes https://github.com/bootscore/bootscore/issues/491
=> Small fixes

inc/scssphp/composer.json, inc/scssphp/src/Compiler.php, inc/scssphp/src/Parser.php, inc/scssphp/src/Version.php
=> Update scssphp 1.11.1

inc/theme-setup.php
- Add support for validated HTML5 script and style tags
- Add support for HTML5 Search Form
=> HTML5 Support

scss/bootscore/_colors.scss
Major accessibility issue (remove tab outline)
Closes https://github.com/bootscore/bootscore/issues/604
=> Fix accessibility behavior

scss/bootscore_woocommerce/_wc_cart.scss, woocommerce/content-product.php, woocommerce/inc/wc-deprecated.php, woocommerce/inc/wc-loop.php
Closes https://github.com/bootscore/bootscore/issues/542
- Go to shop https://dev.bootscore.me/shop/ and add "Album" and "Beanie with Logo" to the cart
- Go to cart page
=> Enable cross sell products

README.md
I have rewritten the entire README.md https://github.com/bootscore/bootscore/tree/Rewrite-readme.md.
- Logo supports now dark-mode. View README.md and enable dark-mode on your OS.
- Ukraine banner: We're listed https://github.com/vshymanskyy/StandWithUkraine next to big projects like Symfony and get a lot of traffic from there. That's why I want to keep banner but I made it a bit smaller and moved it below the title for less dominance.
- Table of contents.
- Mention the sponsorship
@justinkruit if you like it, merge it!
=> Rewrite readme.md

inc/scssphp/src/Compiler.php, inc/scssphp/src/OutputStyle.php, inc/scssphp/src/Parser.php, inc/scssphp/src/Version.php
=> Update scssphp 1.12.0

inc/enqueue.php, woocommerce/inc/ajax-add-to-cart.php, woocommerce/inc/wc-enqueue.php, woocommerce/inc/wc-mini-cart.php, woocommerce/inc/wc-qty-btn.php
@anisur2805 if you want to have a quick look to it would be very nice.
=> Fix Ajax path

assets/scss/bootscore-woocommerce/_wc-my-account-offcanvas.scss, template-parts/header/actions-woocommerce.php, template-parts/header/offcanvas-woocommerce.php, woocommerce.php, woocommerce/myaccount/my-account-offcanvas.php, woocommerce/myaccount/navigation.php
Closes https://github.com/bootscore/bootscore/issues/687
Closes https://github.com/bootscore/bootscore/pull/635
=> Replaced `my-account-offcanvas.php` with `my-account.php` in user offcanvas

woocommerce/cart/mini-cart.php
- https://dev.bootscore.me/product/beanie/
- https://dev.bootscore.me/product/hoodie-with-pocket/
=> Add badge to offcanvas cart if product is sold individually or less than 6 in stock left

assets/scss/main.scss
This got lost in https://github.com/bootscore/bootscore/pull/645
=> Add Bootstrap copyright banner

woocommerce/inc/wc-skip-cart.php
See https://github.com/bootscore/bootscore/pull/816#issuecomment-2282116522
=> Skip redirect cart to checkout if cart is empty

footer.php, header.php
=> Add a skip to footer link [Feature Request] #916

footer.php, functions.php, header.php, inc/tinymce-editor.php, searchform.php, template-parts/header/actions-woocommerce.php, template-parts/header/actions.php, template-parts/header/offcanvas-woocommerce.php
aria-label for hamburger menù
Closes https://github.com/bootscore/bootscore/issues/934
=> aria-label for hamburger menù

searchform.php
ARIA role="search" added in HTML
=> Update searchform.php for accessibility

assets/scss/bootscore-woocommerce/_wc-loop.scss, woocommerce/content-product-cat.php, woocommerce/content-product.php, woocommerce/inc/wc-loop.php
- `bootscore/class/woocommerce/product/card`, content-product.php, content-product-cat.php
- `bootscore/class/woocommerce/product/card/card-body`, content-product.php, content-product-cat.php
- `bootscore/class/woocommerce/loop/add-to-cart`, wc-loop.php
- `bootscore/class/woocommerce/product/loop/img`, wc-loop.php
- `bootscore/class/woocommerce/category/loop/img`, wc-loop.php
- `bootscore/class/woocommerce/loop/add-to-cart/button`, wc-loop.php
```php
/**
* Remove WC loop images
*/
function bootscore_remove_loop_images() {
// Ensure product images are completely removed
remove_action('woocommerce_before_shop_loop_item_title', 'bootscore_loop_product_thumbnail', 10);
remove_action('woocommerce_before_shop_loop_item_title', 'woocommerce_template_loop_product_thumbnail', 10);
// Ensure …
```
=> Add more filters to WC product loop

inc/tinymce-editor.php
Closes https://github.com/bootscore/bootscore/issues/974
=> Fix TinyMCE editor-style

assets/scss/bootscore-woocommerce/_wc-colors.scss, assets/scss/bootscore-woocommerce/_wc-deprecated.scss, assets/scss/bootscore-woocommerce/_wc-forms.scss
=> Fix WC 9.8 star and password icons color

woocommerce/inc/wc-ajax-login.php
Enhances IP address retrieval to accommodate hosts that do not populate standard $_SERVER variables correctly.
This ensures reliable IP detection across a wider range of server configurations.
Discussion: https://github.com/orgs/bootscore/discussions/1049,
=> Improves IP address detection

assets/scss/bootscore-woocommerce/_wc-comments.scss, assets/scss/bootscore/_colors.scss, assets/scss/bootscore/_markups.scss, functions.php, inc/blocks/block-code.php
=> Minor CSS fixes

footer.php, readme.txt
- Added role="button" for screen reader compatibility
- Removed visually-hidden span and used aria-label for translation support
Closes https://github.com/bootscore/bootscore/issues/1060
@neralex Do you agree with this changes?
=> Improve accessibility of the to top button

assets/scss/bootscore-woocommerce/_wc-loop.scss, woocommerce/inc/ajax-cart.php, woocommerce/inc/wc-loop.php, woocommerce/inc/wc-stock-badge.php
```php
/**
* Disable loop out-of-stock-badge
*/ 
add_filter('bootscore/loop/out-of-stock-badge', '__return_false');
```
=> Improve out-of-stock handling in loop

woocommerce/inc/wc-setup.php, woocommerce/inc/wc-single-product-reviews.php, woocommerce/js/woocommerce.js
=> Fix WC reviews mail and name form if comments are open to everybody
