bootscore/bootscore

- index.php
The default for `col` is to have max-width set to 100%, sadly, this means that if there is content (such as a large image) that takes more then `calc(100%-25%)` of viewport, then the menu on the RHS will not show.
This tiny PR sets a width for the column, which ensures that the menu will appear on the RHS. Ideally, there would be a check here to ensure that the `col-md-7` is only applied when the sidebar has content.
> Ensure that the rhs column has a set width

- woocommerce/css/woocommerce-style.css
As per issue #12, we decided that it's a good idea to give Woocommerce classes that call a Bootstap variable a custom bootScore variable that isn't set by default. That way you can easily override specific colors, and don't have to worry about updates to the Woocommerce files.
> Giving Woocommerce styles custom variables

- woocommerce/checkout/terms.php
I wrapped the "getCorrectedTerms" around all hooks in that file (maybe no necessary), but it should only affect "correct" formated parts. (Tested with sendinblue newsletter plugin)
> Built a "filter" for terms.php

- woocommerce/js/woocommerce.js
- woocommerce/myaccount/my-account-offcanvas.php
- woocommerce/woocommerce-functions.php
Closes #35 
This PR removes the hook for alerts in user offcanvas and redirects to my-account page if login failed.
Before logged in via user offcanvas and entered a wrong password or username, offcanvas stayed open and alert was displayed inside offcanvas. This makes problems if a user edited data in dashboard. For example when changing the address, the alert for failed or success were shown in offcanvas too.
Now the hook for alerts is removed and user will be redirect to my-account page when login failed instead and alert is shown there. 
- Redirect to my-account page after login in offcanvas failed
- Redirect to my-account page after login in checkout failed
- Redirect to home page after logout
- Alerts in dashboard are shown in the top of the page when changing data there
Code is …
> Added redirect if offcanvas login failed

- inc/scss-compiler.php
When `wp_get_environment_type()` returns that it is in development mode, either from reading the `define` in the wp-config.php or from reading the `getenv`, the scss will always be compiled, no matter if changes have been made.
To set the environment to development, add the following line to your wp-config.php
`define('WP_ENVIRONMENT_TYPE', 'development');`
This PR has been made in response to comments from @Axos11 on #33
> Force scss compile when environment is development

- footer.php
- header-woocommerce.php
- header.php
- searchform.php
- woocommerce/product-searchform.php
It's not possible to add a `<label>` to searchform.php because form has no id. The searchform can't have an id because it will be displayed twice if it is in the top-nav-search widget position, mobile and large. In this case the id will be double. So, still remaining two accessibility errors.
> Fix accessibility issues

- css/scss/_bscore_custom.scss
- css/scss/_bscore_style.scss
- css/scss/_bscore_woocommerce.scss
- css/scss/bootstrap.min.scss
This PR adds a (still empty) `_bscore_woocommerce.scss` collector file and prepares to merge the `woocommerce-style.css` to scss like we did with style.css. This file is deactivated in parent `_bootstrap.min.scss` and can be activated by removing the comments. bootcommerce-child has activated this file by default Pull request [#5](https://github.com/bootscore/bootcommerce-child/pull/5).
File is loaded before `_bscore_custom.scss` and can easily be overwritten.
We should users give time to add this file by `@import` on their existing bootcommerce-child theme installation. In 5.2.1.0 we can move content from `woocommerce-style.css` to scss safely.
> Woocommerce-style.css to scss part 1

- js/theme.js
Closes #71 
This PR removes the self-closing offcanvas in navbar on resize workaround, which became buggy in iOS 15.
- Navbar offcanvas will do not close on resize anymore
- When resize through the breakpoints, backdrop remains visible and body scroll locked
- Will be fixed by https://github.com/twbs/bootstrap/issues/35594
> Remove self closing offcanvas snippet

- inc/scss-compiler.php
This should fix #103. @crftwrk could you try this out on the installations you stumbled upon this issue? I've tried it in a test environment, and it seems to work fine now.
> Fix for scss .map when using subdirectory

- js/theme.js
This PR removes the dropdown slide effect. It's buggy with rtl and dropdown position. Users who want to use slide effect should add snipped to their child.
```js
jQuery(function ($) {
// Dropdown menu animation
// Add slideDown animation to Bootstrap dropdown when expanding.
$('.dropdown').on('show.bs.dropdown', function () {
$(this).find('.dropdown-menu').first().stop(true, true).slideDown();
});
// Add slideUp animation to Bootstrap dropdown when collapsing.
$('.dropdown').on('hide.bs.dropdown', function () {
$(this).find('.dropdown-menu').first().stop(true, true).slideUp();
});
});
```
> Remove dropdown slide effect

- scss/bootscore_woocommerce/_wc_product.scss
Closes https://github.com/bootscore/bootscore/issues/118
Fixes related products if no product tab (disabled reviews, no product description, no attributes) is used
> Add clear: both; to related products

- woocommerce/woocommerce-functions.php
This PR turns the register ajax-add-to-cart.php to a pluggable function. If someone want to create an affiliate shop, it's possible to disable ajax cart by using empty function in child:
```php
// Disable Ajax Cart
function register_ajax_cart() {
}
add_action('after_setup_theme', 'register_ajax_cart');
```
> Register ajax cart to pluggable function

- scss/_bscore_style.scss
- scss/bootscore/_admin_bar.scss
- scss/bootscore/_footer.scss
- scss/bootscore/_header.scss
- scss/bootscore/_markups.scss
- Added `_admin_bar.scss`
- Moved `.logged-in.admin-bar` from `_header.scss` to `_admin_bar.scss`
- Added `_footer.scss`
- Moved sticky footer from `_markups.scss` to `_footer.scss`
We can handle sticky footer if user is logged in in `_admin_bar.scss` later.
> Improve admin bar

- functions.php
I've renamed the bootscore_comment_form() function to bootscore_comment_button() for clarity.
I also made both the bootscore_comment_button() and the bootscore_pw_form() functions pluggable to allow them to be overridden in the functions.php file of the child theme.
> Pluggable comment button and pw form

- scss/bootscore_woocommerce/_wc_offcanvas_cart.scss
- woocommerce/cart/mini-cart.php
This PR removes `border-bottom p-3` classes and uses `list-group list-group-flush` component for offcanvas cart-items instead.
There is also a small improvement with the height of `cart-list`. If there are many products in the cart, the scrollbars will not cover `cart-footer` anymore.
Preview https://dev.bootscore.me/shop/
@justinkruit If you agree, I'm happy when you just hit the merge button.
> Offcanvas cart-items to list-group-flush

- scss/bootscore_woocommerce/_wc_cart.scss
This PR fixes the coupon in cart page on small devices. In languages with long words, the `input-group` breaks into 2 lines because input has `width: 48%` by WooCommerce. Now this is overridden with default Bootstrap `.input-group` > `form-control` `width: 1%`.
> Fix coupon input in cart page

- functions.php
This is for users who are still afraid to touch a .scss file. So, they can do overrides in style.css without the `!important` rule.
> Load style.css after main.css

- woocommerce/js/woocommerce.js
Based on #200, now the product offcanvas only opens when adding a simple product in an archive, or when adding any product on the single page.
> Improve WC product offcanvas

- woocommerce/js/woocommerce.js
Reverts bootscore/bootscore#205
@justinkruit had to revert this, because it doesn't work if products are outside the loop. For example here https://bootscore.me/#download
Maybe, we should find another solution.
> Revert "Improve WC product offcanvas"

- scss/bootscore/_temporary.scss
Not needed anymore https://github.com/bootscore/bs-cookie-settings/commit/24a6cc79ac84308658bbd6e1929a5dbece57216c#diff-ce421381cad6a75a50fd363e6d89ad076f7c5a5cf32efe940f22f0420b379c1c
> Remove bS Cookie Settings modal fallback

- scss/bootscore/_header.scss
This snippet added an edge to edge last nav-link to container if no header widget is active. I'm not sure if we should keep this or following more the Bootstrap way and delete it.
> Remove nav-link last-child padding

- scss/_bscore_woocommerce.scss
- scss/bootscore_woocommerce/_wc_my_account_offcanvas.scss
- woocommerce/myaccount/my-account-offcanvas.php
This PR adds the missing show-password in user offcanvas in non WooCommerce pages. Tested and works fine, already live on https://bootscore.me/.
| non Woo pages  | Woo pages |
| ![before](https://user-images.githubusercontent.com/51531217/210793348-46cb9491-fcf2-4525-bc1e-fed0e8f409a5.png)  | ![shop-page](https://user-images.githubusercontent.com/51531217/210793494-184fb91e-2e9c-46d0-9cbe-7b0fa2e1bcb1.png)  |
| non Woo pages  | Woo pages |
| ![after](https://user-images.githubusercontent.com/51531217/210793993-892b0e48-24dc-40cf-8ae8-170e9dbb37b9.png)  | ![shop-page](https://user-images.githubusercontent.com/51531217/210793494-184fb91e-2e9c-46d0-9cbe-7b0fa2e1bcb1.png)  |
> Add show-password to all pages in user offcanvas

- inc/class-bootstrap-5-navwalker.php
- js/theme.js
https://github.com/bootscore/bootscore/discussions/347
> Prevent self-closing offcanvas if dropdown has a nested dropdown (modified nav-walker with 3 or more levels depth)

- scss/bootscore/_admin_bar.scss
The title says it all. Previously it set the top with a breakpoint, but WordPress provides a css variable that automatically sets the height. The 32px is just as a failsafe.
> Make use of admin bar height css var for offcanvas and modal

- inc/scss-compiler.php
This will add more control for the user over the SCSS compiler. You'll be able to disable the environment check (don't always compile in development or local) or disable the compiler completely.
**Priority of checking:**
1. If filter has been added
2. If a constant has been set
3. Fall back to `false`
Below the new filters, constants, and how to use them.
* Filter: `bootscore_scss_disable_compiler`
* `add_filter('bootscore_scss_disable_compiler', '__return_true');`
* Constant: `BOOTSCORE_SCSS_DISABLE_COMPILER`
* `define('BOOTSCORE_SCSS_DISABLE_COMPILER', true);`
* Filter: `bootscore_scss_skip_environment_check`
* `add_filter('bootscore_scss_skip_environment_check', '__return_true');`
* Constant: `BOOTSCORE_SCSS_SKIP_ENVIRONMENT_CHECK`
* `define('BOOTSCORE_SCSS_SKIP_ENVIRONMENT_CHECK', …
> Add more control over scss compiler

- functions.php
This PR adds `card-header` to sidebar widget cards. 
Demo: https://dev.bootscore.me/shop/
If no widget title is defined, `card-body` will not be added. Remove card border by using silent class like search widget.
```css
#secondary .widget_product_search.card {
border: none;
}
```
| ![before](https://user-images.githubusercontent.com/51531217/226837528-231a8afd-046e-4bf3-b64c-7540d1da0579.png)  | ![after](https://user-images.githubusercontent.com/51531217/226837590-1d73e2cc-ac51-4179-979a-dcc3982625e9.png)  |
> Add card-header to sidebar widget-cards

- woocommerce/ajax-cart/ajax-add-to-cart.php
- woocommerce/woocommerce-functions.php
Make it so some of the translations are being loaded from Woocommerce. Saves us making translations.
> Use WC strings instead of bootScore in mini cart

- scss/_bscore_woocommerce.scss
- scss/bootscore_woocommerce/_wc_temporary.scss
This PR hides the duplicate empty mini-cart message in cart page. Seems that this came with one of the last Woo updates.
- https://bootscore.me/shop/
- Add something to the cart and go to cart page
- Remove all products in cart page with the recycle bin. 
- `No products in the cart` mini-cart message appears here
- Do the same here https://dev.bootscore.me/shop/
Think we should do a release soon.
> Hide duplicate empty mini-cart message in cart page

- comments.php
- inc/comment-list.php
- scss/bootscore/_comments.scss
- scss/bootscore_woocommerce/_wc_alerts.scss
- scss/bootscore_woocommerce/_wc_comments.scss
This PR improves the comment section by spacing utilities, some alerts and a `card-text` clone to remove bottom-margin from last `<p>` in comment cards. No breaking changes
Demo: 
- https://dev.bootscore.me/2012/01/03/template-comments/
- https://dev.bootscore.me/2012/01/01/template-pingbacks-an-trackbacks/
- https://dev.bootscore.me/product/album/#reviews
- https://dev.bootscore.me/product/beanie-with-logo/#reviews
@justinkruit if you agree, I'm happy when you just hit the merge button.
> Improve comments section

- footer.php
- functions.php
- header-woocommerce.php
- header.php
- js/theme.js
- scss/bootscore/_widgets.scss
- sidebar.php
This PR registers 2 new widgets and fixes existing issues. No breaking changes.
Demo: https://dev.bootscore.me/
Closes https://github.com/bootscore/bootscore/issues/444
| Mobile  | Mobile |
| ![mobile](https://user-images.githubusercontent.com/51531217/232004488-7a99e14c-c9a5-4aa0-8b95-be595ddce6c6.png) | ![top-nav-2](https://user-images.githubusercontent.com/51531217/232004597-4f1bf3b0-cc9f-490d-9c8c-37df0729308c.png) |
- New `Top Nav 2` widget. While the existing `Top Nav` widget stays in navbar on `<lg` screen, `Top Nav 2` moves to offcanvas. Very usefull if you want to move for example the search widget to offcanvas on mobile.
- General clean-up and reorder widgets HTML. No empty `<div>`'s anymore if widget is not active. Uses `<?php if …
> Add 2 more widget areas and improve existing ones

- scss/bootscore_woocommerce/_wc_checkout.scss
There are a lot of `!important` because Woo has horrible selectors. But ok for me.
| <img width="384" alt="before" src="https://user-images.githubusercontent.com/51531217/232745747-28febef4-3851-46ce-ae35-d2be7d98cba3.png">  | <img width="385" alt="after" src="https://user-images.githubusercontent.com/51531217/232745737-7db67dfd-89a3-42dd-ac72-cdd22c913a21.png">  |
> Fix checkout payment checks & radios

- functions.php
- scss/bootscore/_recycle_bin.scss
Fixes rough the input-group border-radius in pw protected form. Function creates `<br>` tags.
| <img width="471" alt="Bildschirmfoto 2023-05-30 um 11 48 10" src="https://github.com/bootscore/bootscore/assets/51531217/580be7c6-b767-4e5b-a898-9b821fbadbe6">  | <img width="477" alt="Bildschirmfoto 2023-05-30 um 11 47 36" src="https://github.com/bootscore/bootscore/assets/51531217/3e1cf895-366e-480c-b354-f075667ed25e">  |
> Hotfix password protected form

- woocommerce/wc-functions.php
- Correct way to `wp_enqueue_script('wc-cart-fragments');` (urgent, my bad)
- Rename 2 functions (minor)
Fixes https://github.com/bootscore/bootscore/issues/502
@justinkruit if you agree, please merge
> Fix enqueue cart fragments script

- functions.php
Following  #511 
Changing `ms-2` to `ms-1 ms-md-2` in top-nav-widget. So if we add items or buttons via `wordpress admin panel` to the top-nav widget, one after another in different `HTML-code` container blocks, we would keep 0.25rem margin between them on mobile screens instead of ms-2, which would look too wide compared to margin between other elements (navbar-toggler, search, cart, user — all of them use ms-1 on mobile). So we won't see this:)
Closes https://github.com/bootscore/bootscore/issues/511
> Changing ms-2 to ms-1 ms-md-2 in top-nav-widget

- woocommerce/cart/cart.php
- woocommerce/cart/mini-cart.php
This PR updates `cart.php` and `mini-cart.php` for upcoming WooCommerce 7.9 (July 11th) release. I hate maintaining WC templates, so this two files are the next ones on my removing list ;-)
Tested it with WC 7.8.2 as well and works fine, we can safely merge.
@justinkruit think we should https://github.com/bootscore/bootscore/pull/520 first. If both PR's are merged, I will prepare a release for 5.3.1 which we should ship on Monday. Agree?
> Update WooCommerce 7.9 templates

- readme.txt
- scss/_bscore_style.scss
- scss/_bscore_woocommerce.scss
- single-templates/single-full-width-image.php
- single-templates/single-sidebar-left.php
- single-templates/single-sidebar-none.php
- single.php
- style.css
This PR updates the version numbers and adds a hook to all `single-*php`'s. Tested it on some live-sites and works fine.
Some users asked for related posts and I think this is a nice feature. But we should not add this feature direct to the theme, we can use the Grid or Swiper plugin to do that. So, the plan is to add a related posts template to one of those plugins and if plugin is installed, related posts hook there. 
Here is a quick preview: https://intelligent-heizen.info/energieeffizient-bauen-so-gehts/. Scroll down to the bottom, above the pagination there are related posts showing the latest 12 posts from the same category using the bS Swiper plugin.
@justinkruit as usual, there is a drafted release ready to publish.
> 5.3.1 Release

- scss/bootscore_woocommerce/_wc_breadcrumb.scss
- scss/bootscore_woocommerce/_wc_cart.scss
- scss/bootscore_woocommerce/_wc_qty_btn.scss
- woocommerce/wc-functions.php
Closes https://github.com/bootscore/bootscore/issues/538
Demo https://dev.bootscore.me/shop/
As discussed in https://github.com/bootscore/bootscore/pull/535, this PR makes the qty always visible and fixes overflow text in mobile cart coupon button for languages with longer words.
| Before | After |
| Default product  | No changes  |
| 1 in stock qty hidden  | 1 in stock qty visible but disabled  |
| Sold individually qty hidden  | Sold individually qty visible but disabled  |
| Cart 1 in stock qty visible, can be set to 0  | No changes  |
| Cart sold individually qty hidden  | Cart sold individually qty visible, can NOT be set to 0  |
| ![default-before](https://github.com/bootscore/bootscore/assets/515 …
> Make qty always visible

- functions.php
- inc/columns.php
- sidebar.php
Think this PR speaks for itself. Change the entire main/sidebar columns and breakpoints in one file.
@justinkruit if you like it, merge it. Are you able to publish a release next Monday?
> Use function for sidebar col width and responsive offcanvas

- scss/_bscore_style.scss
- scss/bootscore/_forms.scss
- scss/bootscore/_functions.scss
- scss/bootscore_woocommerce/_wc_checkout.scss
Refactored the checkout again. Validation can now be made by CSS variables in other forms (contact forms etc.) as well without using JS. Code is much more cleaner and saves around 10kb in compiled CSS output. Tested on several live shops and works fine.
@justinkruit if you like it merge it.
> Improve checkout form validation

- scss/bootscore_woocommerce/_wc_loop.scss
- woocommerce/inc/wc-loop.php
Per https://github.com/orgs/bootscore/discussions/597
This adjustment is in-line with effort to reduce WC templates #333
[IMPROVEMENT] Removed func custom_loop_product_thumbnail() from bootscore/woocommerce/inc/wc-loop.php
[IMPROVEMENT] Modified bootscore/woocommerce/inc/wc-loop.php to fetch both, category and product loop images
The above changes allow the following to work as expected:
// Remove product thumbnails from the shop loop:
remove_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_template_loop_product_thumbnail', 10 );
On branch reduce-WC-templates
Your branch is up to date with 'origin/reduce-WC-templates'.
Changes to be committed:
modified:   scss/bootscore_woocommerce/_wc_loop.scss
modified:   woocommerce/inc/wc-loop.php
> An adjustment that enables removing shop thumbnails in a supported way.

- inc/pagination.php
- [Fixed] Replace `sr-only` with `visually-hidden` as per Bootstrap 5.3. Fixes #614
> Replace sr-only with visually-hidden

- woocommerce/inc/ajax-add-to-cart.php
https://github.com/bootscore/bootscore/pull/574/commits/07ec79f661bd50ccb44556604736c02e6e8e7525 added the `.woocommerce-info` selector. As a result, empty cart message removes if offcanvas cart opens twice. This PR excludes the empty cart message selector.
> Exclude empty cart message from remove if offcanvas cart gets closed

- inc/enqueue.php
- inc/pagination.php
- js/theme.js
- [Changed] Removed navigation role from nav element as per HTML5 standards. See #619 
- [Removed] Remove IE Support and warning. See #617 
Closes https://github.com/bootscore/bootscore/issues/619
Closes https://github.com/bootscore/bootscore/issues/617
> HTML5 Compliance, Remove IE warning alert

- footer.php
- inc/widgets.php
This PR changes the footer widget 1-4 `col-md-6` to `col-6` and the bottom margin from `mb-4` to `mb-3`. Less whitespace and a much more modern look & feel.
| ![footer-1](https://github.com/bootscore/bootscore/assets/51531217/f1bada1d-b0d2-4bbf-9929-839adddc68ad)  | ![footer-2](https://github.com/bootscore/bootscore/assets/51531217/69dc1243-66d7-4f42-8887-4ca51f5a2fb8)  |
> Change footer `col-md-6` to `col-6`

- scss/_bscore_utilities.scss
- scss/main.scss
In issue #640 we highlighted that a rewrite of the `main.scss` is needed to give the users more control over Bootstrap. With this PR that will be achieved.
The variables are set before Bootstrap so everything is better overridable. 
A new `_bscore_maps.scss` has been added so maps can also be overridden. 
And lastly a new `_bscore_utilities.scss` has been added and loaded _after_ the Bootstrap utilities so they can be added upon ([docs](https://getbootstrap.com/docs/5.3/utilities/api/#using-the-api)).
I've tested the compiling locally, and nothing seems to be missing.
@crftwrk If you like it, merge it. 😜
> Rewrite main.scss

- functions.php
- inc/widgets.php
This PR removes the filter which enables classic widgets by default. I think we should let users decide by them self if they want to use Gutenberg or classic widgets by adding the filter to their child or installing the https://wordpress.org/plugins/classic-widgets/ plugin. 
The reason why I've added the filters was the search widget. Now Gutenberg search widget is used which is very ugly, but maybe this forces us to do something more to support blocks. When PR is merged, I will fix the Gutenberg search block.
@justinkruit IYLIMI!
> Remove filter to enable classic widgets by default

- woocommerce/loop/pagination.php
Closes https://github.com/bootscore/bootscore/issues/661
Demo https://dev.bootscore.me/shop/wc-shortcodes/
This PR fixes the WC pagination if a shortcode has limited products and pagination is set to true `[products on_sale="true" per_page="2" paginate="true"]`.
@justinkruit IYLIMI
> Fix WC pagination.php

- inc/theme-setup.php
This PR allows to use blocks as template parts. In Backend Appearance > Template Parts can now the mini-cart edited in more detail and we can hard code it in the theme like https://github.com/woocommerce/storefront/pull/2100.
Think in the long-term, our offcanvas-cart should be replaced by the mini-cart block https://github.com/bootscore/bootscore/issues/631.
Did roughly some changes to demonstrate how it works:
- Go to https://dev.bootscore.me/shop/ and add something to the cart
- Scroll down to the footer, there you will find the Woo mini-cart block. Open cart and check buttons, they have classes `btn btn-primary` etc.
@justinkruit IYLIMI
> Add theme support for block template-parts

- header.php
- template-parts/header/actions-woocommerce.php
- template-parts/header/actions.php
```php
/*
* Header position and bg
*/
function header_bg_class() {
return "sticky-top bg-body shadow";
}
add_filter('bootscore/header_class', 'header_bg_class', 10, 2);
```
```php
/*
* Header buttons
*/
function header_button_class() {
return "btn btn-link ps-2 pe-0 text-decoration-none text-body-secondary";
}
add_filter('bootscore/header_button_class', 'header_button_class', 10, 2);
```
> Add more filters to header

- footer.php
```php
/*
* Footer classes
*/
function footer_class() {
return "bg-dark text-white pt-5 pb-3";
}
add_filter('bootscore/footer_class', 'footer_class', 10, 2);
```
```php
/*
* Footer info
*/
function footer_info_class() {
return "bg-dark text-white border-top border-secondary py-2 small";
}
add_filter('bootscore/footer_info_class', 'footer_info_class', 10, 2);
```
```php
/*
* Change to-top button classes
*/
function footer_to_top_button_class() {
return "btn btn-sm btn-outline-secondary rounded-pill shadow-lg";
}
add_filter('bootscore/to_top_button_class', 'footer_to_top_button_class', 10, 2);
```
> Add filters to footer

- 404.php
- archive.php
- footer.php
- header.php
- inc/columns.php
- inc/deprecated.php
- index.php
- page-templates/page-blank-with-container.php
- page-templates/page-full-width-image.php
- page-templates/page-sidebar-left.php
- page-templates/page-sidebar-none.php
- page.php
- search.php
- sidebar.php
- single-templates/single-full-width-image.php
- single-templates/single-sidebar-left.php
- single-templates/single-sidebar-none.php
- single.php
- template-parts/header/actions-woocommerce.php
- template-parts/header/actions.php
- template-parts/header/top-nav-search-collapse-woocommerce.php
- template-parts/header/top-nav-search-collapse.php
- woocommerce.php
- Renamed `bootscore/header_button_class` to `bootscore/header/button_class` and added which button it is.
I'm also now debating, what would be better filter names?
| Current | Idea |
|--------|--------|
| `bootscore/header_button_class` | `bootscore/class/header_button` | 
| `bootscore/header_class` | `bootscore/class/header` | 
| `bootscore/container_class` | `bootscore/class/container` | 
This idea is coming from the principle of merging things that are alike, like the filter `bootscore/offcanvas/navbar/title`. With the other filters, we do nothing more than managing their classes. So a `bootscore/container/class` would imply more things happening with the container. I'm open to feedback @crftwrk
> Rename some new filters

- woocommerce/cart/mini-cart.php
- woocommerce/inc/ajax-cart.php
@crftwrk please review the changes and let me know the feedback.
> Fix: Tax include and exclude subtotal in WC Mini Cart.

- woocommerce/inc/ajax-cart.php
Closes https://github.com/bootscore/bootscore/issues/532
I identified some strange behaviors in the add to cart function with AJAX, as also reported in #532  and decided to investigate.
I noticed that when we are not on the product's single page, the AJAX request to add the product to the cart happens twice. One started by WooCommerce's `/plugins/woocommerce/assets/js/frontend/add-to-cart-min.js` file and another started by Bootscore's https://github.com/bootscore/bootscore/blob/v6.0.0-beta1/woocommerce/inc/ajax-cart.php file by the function that starts at line 100 and ends at line 168. It seems that when the request coming from bootscore is completed too early (before the one from WooCommerce), bugs occur such as: The product added to cart notification is removed shortly after being …
> [FIX] [BUG] Duplicate wc-ajax=add_to_cart

- README.md
There went something wrong in https://github.com/bootscore/bootscore/pull/819. Copyright isn't merged into `main.scss`
> Add Bootstrap copyright banner

- assets/scss/bootscore-woocommerce/_wc-breadcrumb.scss
- woocommerce/inc/wc-breadcrumb.php
This PR brings back the `Home` to WC breadcrumb, because as discussed in https://github.com/orgs/bootscore/discussions/775, the `Home` value of Breadcrumb is recognized as empty by Google so far.
Unfortunately, it's not possible to add the icon with a filter, because WC escapes the HTML and overriding WC's `breadcrumb.php` template is not an option anymore https://github.com/bootscore/bootscore/issues/333.
As a workaround `text-indent` is used to move the word `Home` out of the screen (but visible for Google) and adds the home icon as a `mask-image` pseudo class like done before. There are no visual changes in the frontend.
cc @stan1781
> Fix: Empty `Home` value in WC breadcrumb

- assets/scss/bootscore-woocommerce/_wc-qty-btn.scss
- woocommerce/inc/ajax-cart.php
Closes https://github.com/bootscore/bootscore/issues/801
I solved this now using jQuery to get rid of the SCSS selector. It's not an elegant way, but it works and I think this is just temporary and we can revert this PR when scssphp v2 has fixed this. For this reason, the scss snippet is just commented out.
Go to https://dev.bootscore.me/product/beanie/, add product to the cart and check quantity input and buttons in offcanvas cart. Input and buttons are disabled, because this product has quantity `max="1"` attribute.
Edit: check https://github.com/bootscore/bootscore/pull/827
> Fix: Compile error using woocommerce css

- inc/widgets.php
Moved the "widget" class from the `<h2> ` tag to the parent `<div>`  in Footer 4 widget area
> Footer 4 "widget" class assigned to wrong element

- template-parts/header/actions-woocommerce.php
- template-parts/header/offcanvas-woocommerce.php
This pull request introduces a new filter 'bootscore/enable_account' that, when applied, will hide the user account button and the associated offcanvas flyout. 
This is especially useful for WooCommerce sites that are designed to be anonymous guest-only transactional sites, where displaying account options is unnecessary.
Key Changes:
Added a new filter ensures that the user account UI elements are not displayed, making the site more suited for anonymous transactions.
This change was discussed and referenced in a [GitHub discussion](https://github.com/orgs/bootscore/discussions/880)
Testing
After applying the filter
```
/**
* Disable WooCommerce account
*/
add_filter('bootscore/enable_account', '__return_false');
```
the user account button and the offcanvas components are be removed from …
> Add filters to enhance WooCommerce header and offcanvas user account 

- assets/scss/bootscore-woocommerce/_wc-product-variable.scss
- woocommerce/cart/mini-cart.php
- Update: `mini-cart.php` (WC 9.5)
- Fix: Table and clear button in variable product page (WC 9.5 changes the `<a>` to `<button>` element)
| <img width="411" alt="before-1" src="https://github.com/user-attachments/assets/349acfba-7308-4a08-a31c-def4feb09f70">  | <img width="407" alt="after-1" src="https://github.com/user-attachments/assets/1c1313a0-e9a8-40eb-a0fe-579e252fe6a4">  |
| <img width="411" alt="before-2" src="https://github.com/user-attachments/assets/90313026-d6bf-4afd-8520-fd398ebd45a4">  | <img width="405" alt="after-2" src="https://github.com/user-attachments/assets/ade30f57-66c1-4785-af53-a2e06721d907">  |
> Update WC 9.5 templates

- assets/scss/bootscore/blocks/_blocks.scss
- Fix: - `rounded` class only to selected block image instead adding class to all images inside a `rounded wrapper` https://github.com/bootscore/bootscore/pull/889/commits/aa32ecec3c059dd80b1810e6a371b928968505d8
- Added more `rounded-*` classes to the image block https://github.com/bootscore/bootscore/pull/889/commits/bd88a8e345904b3cd06956fa16dfa92c2cc214ef
- Added dark-mode support to gallery/img block lightbox https://github.com/bootscore/bootscore/pull/889/commits/f132631e65d64b9355b0430e80dd107ec34a58fa
> Minor SCSS fixes

- inc/enqueue.php
Adds missing compiled styles to the WP pattern editor to show patterns correctly **Backend > Appearance > Patterns**
| ![before](https://github.com/user-attachments/assets/ecf37137-b268-4806-a456-3445596488d1)  | ![after](https://github.com/user-attachments/assets/0a1bef86-0001-4c24-a8e0-1ef2c772b8c9)  |
> Enqueue main.css to WP Pattern Editor

- woocommerce/inc/wc-forms.php
Update snippet to replace woo Select2 even on cart and checkout blocks.
Closes https://github.com/bootscore/bootscore/issues/918
> Remove select2 scripts and styles on blockified classic checkout

- woocommerce/inc/wc-forms.php
@MicheleGrimaldi unfortunately figured out that this creates a bug with Stripe which makes it impossible to pay by credit card. I quickly commented the code to revert your PR and reopened the issue. So we have to check and fix this later. Until this has been solved, please use shortcode in checkout instead the blockified classic cart as described in the [docs](https://bootscore.me/documentation/woocommerce/#cart-and-checkout-since-wc-8-3).
- https://github.com/bootscore/bootscore/issues/918
- https://github.com/bootscore/bootscore/pull/919
> Revert #919

- index.php
WordPress places sticky posts at top of a main query already, so this index.php has one query instead of two, taking advantage of that built-in feature. @crftwrk
> Refactor loop in index.php

- assets/scss/bootscore-woocommerce/_wc-checkout.scss
- assets/scss/bootscore-woocommerce/_wc-my-account.scss
- assets/scss/bootscore-woocommerce/_wc-product-variable.scss
| <img width="283" alt="Image" src="https://github.com/user-attachments/assets/be7cdd36-47e0-4db3-927b-8c6dfb53b459" />  | <img width="278" alt="Image" src="https://github.com/user-attachments/assets/8e7e12f9-27e6-4805-9c94-f147f07622e5" />  |
| <img width="280" alt="Image" src="https://github.com/user-attachments/assets/ff0327ef-da20-4b08-809c-9d111e1004c7" />  | <img width="281" alt="Image" src="https://github.com/user-attachments/assets/578e5c8a-6500-43cb-8b23-abbbd2d5a3e2" /> |
| <img width="276" alt="Image" src="https://github.com/user-attachments/assets/c74abe68-571b-46b8-9177-42623702c6de" />  | <img width="273" …
> Minor WC CSS fixes

- patterns/c-alert-danger.php
- patterns/c-alert-info.php
- patterns/c-btn-danger-lg.php
- patterns/c-btn-outline-secondary-sm.php
- patterns/c-btn-primary.php
- patterns/c-card-basic.php
- patterns/c-card-header-footer.php
- patterns/c-card-widget-categories.php
- patterns/c-cards-pricing.php
- patterns/c-hero-img-left.php
- patterns/c-hero-img-right.php
- patterns/c-hero-jumbotron.php
- patterns/l-container.php
- patterns/l-grid-col-3.php
- patterns/l-grid-col-4-col-8.php
- patterns/l-grid-col-6.php
- patterns/l-grid-col-8-col-4.php
- patterns/s-heading-subtitle.php
- patterns/s-hero-img-left.php
- patterns/s-hero-img-right.php
- patterns/s-hero-jumbotron.php
@gorobey I saw that you fixed the bugs with the incorrect pattern names in debug mode https://github.com/bootscore/bootscore/commit/b94f2b4bddf1c0ab3b83650d63f8621edb14db89 coming with v 6.2. I quickly created a  pull request for that. Are you ok that we merge your fix commit to the theme? I think this should be solved soon.
Thank you
> Fix errors in debug mode with incorrect pattern file names

- assets/scss/bootscore/_header.scss
Closes https://github.com/bootscore/bootscore/issues/1062
Scroll-margin (default navbar height) can be changed in the `_custom.scss` file
```scss
:root {
--#{$prefix}scroll-margin-top: 200px;
}
```
> Add a `scroll-margin-top` to id's in main content

- woocommerce/inc/wc-qty-btn.php
Prevents the qty-btn.php changes to be applied when the necessary args are not provided. Somehow the block checkout version calls the file as well.
> Revert changes to qty-btn.php, fix warnings with minimal changes
